
### Filtre par espèce
GET http://localhost:3000/api/animal?species=rat

###species=chat

### Filtre par âge 
GET http://localhost:3000/api/animal?age=2

### Filitre par âge + espèce avec erreur au milieu
GET http://localhost:3000/api/animal?species=chien&prenom=charlotte&age=2&size=petit&gender=f



### Requête GET pour récupérer tous les animaux
GET http://localhost:3000/api/animal
Accept: application/json

### Requête GET pour récupérer un animal par son ID
GET http://localhost:3000/api/animal/72
Accept: application/json

#-------------Requête POST pour créer un nouvel animal (association)-----

### ! SANS TOKEN
POST http://localhost:3000/api/animal
Content-Type: application/json

{ 
  "name": "Janine",
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"F",
  "age": 5,
  "size":"grand",
  "id_association":1

}
###* AVEC TOKEN
POST http://localhost:3000/api/animal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTU3NzY4OSwiZXhwIjoxNzMxNTgxMjg5fQ.dL0m4isDAJRS0bvNQWpXe0bSsLQPrwCyKqlEiW4VFeY

{ 
  "name": "Janine",
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"F",
  "age": 5,
  "size":"grand"
}

#---------------------pour modifier un animal par son ID (association)--------------------

###! SANS TOKEN
PATCH http://localhost:3000/api/animal/85
Authorization: Bearer 
Content-Type: application/json

{
  "species": "Chat Chien",
  "breed": "expérience raté",
  "gender": "M",
  "size": "petit"
}

###* AVEC TOKEN
PATCH http://localhost:3000/api/animal/72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImVtYWlsIjoibWF4aW1lLmNvbGxldEBlbWFpbC5jb20iLCJyb2xlIjoiYXNzb2NpYXRpb24iLCJpYXQiOjE3MzE0MTc4MjAsImV4cCI6MTczMTQyMTQyMH0.ND71Ca1IysFR2ZBm3Ck2BZmdbsTGWaQqPqitOOgJ6OE
Content-Type: application/json

{
  "species": "Chat Chien",
  "breed": "expérience raté",
  "gender": "F",
  "size": "petit"
}


#------------Pour supprimer un animal par son ID (association)-----------


###! SANS TOKEN
DELETE http://localhost:3000/api/animal/115
Accept: application/json


###* AVEC TOKEN

DELETE http://localhost:3000/api/animal/73
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTQxNzc5MSwiZXhwIjoxNzMxNDIxMzkxfQ.6LkXIAhHBzvZ-wdmEFnUVSftLvIaVoUQQkmCq3fd6P0