### ---------Récupérer toutes les familles-(admin asso)--------------
#! SANS TOKEN
GET http://localhost:3000/api/family
Accept: application/json


###* AVEC TOKEN
GET http://localhost:3000/api/family
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzE0MTc4MjksImV4cCI6MTczMTQyMTQyOX0.iMjaGmmJyYJshydelxMHwLmWNVo6u3D_k5bjQX4UADA
Accept: application/json

#----------------Récupérer une famille par son ID (admin asso)----------------

###! SANS TOKEN
GET http://localhost:3000/api/family/1
Accept: application/json


### AVEC TOKEN
GET http://localhost:3000/api/family/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzE0MTc4MjksImV4cCI6MTczMTQyMTQyOX0.iMjaGmmJyYJshydelxMHwLmWNVo6u3D_k5bjQX4UADA
Accept: application/json

### modification d'une family
PATCH http://localhost:3000/api/family/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzE0MTc4MjksImV4cCI6MTczMTQyMTQyOX0.iMjaGmmJyYJshydelxMHwLmWNVo6u3D_k5bjQX4UADA
Content-Type: application/json

{
    "address": "rue de Gisors POOOues",
    "user": {
        "firstname": "Philippe",
        "lastname": "Bourgeois",
        "password": "CoucouToi383!"
    }
}

### Suppression d'une family
DELETE http://localhost:3000/api/family/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzE0MTc4MjksImV4cCI6MTczMTQyMTQyOX0.iMjaGmmJyYJshydelxMHwLmWNVo6u3D_k5bjQX4UADA
Content-Type: application/json